name: pylipd
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.11
  - pytest
  - pandas
  - numpy
  - jupyter
  - jupyterlab
  - pip:
    - pyleoclim
    - git+https://github.com/LinkedEarth/pylipd.git@main

