name: pylipd
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python==3.11.9
  - pytest
  - pandas
  - jupyter
  - numpy
  - jupyterlab
  - pip:
    - pyleoclim
    - openpyxl
    - git+https://github.com/LinkedEarth/pylipd.git@main

