# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: PyLiPD Tutorials
author: Deborah Khider
logo: LinkedEarth_small.png

# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 3600 #remove restrictions on time usage


# Define the name of the latex output file for PDF builds
latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true 
  latex_documents:
    targetname: PyLiPD_Tutorials.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/LinkedEarth/pylipdTutorials  # Online location of your book
  path_to_book: jupyterBook  # Optional path to your book, relative to the repository root
  branch: jupyterbook # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering    : true   # Continuous numbering across parts/chapters

# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)

