name: Build JupyterBook 

on:
  push:
    branches: [ jupyterbook ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

    - name: Checkout files in repo
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pylipd
        environment-file: environment.yml
        python-version: "3.10"
        auto-activate-base: false

    - name: Install JupyterBook
      run: |
        conda activate pylipd
        pip install jupyter-book>=0.7.0b
        conda list
    
    - name: Build the Book
      run: |
        jupyter-book build jupyterBook
    
    - name: GitHub Pages Actions
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./jupyterBook/_build/html

