name: Sync to JupyterBook

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch JupyterBook branch
      run: |
        git fetch origin jupyterbook:jupyterbook

    - name: Checkout JupyterBook branch
      run: |
        git checkout jupyterbook

    - name: Copy data, figures, and notebooks from main
      run: |
        git checkout main -- data figures notebooks
        git add data figures notebooks

    - name: Generate _toc.yml
      run: |
        cat <<EOF > _toc.yml
        format: jb-book
        root: intro
        parts:
          - caption: Dataset Representation in PyLiPD
            chapters:
            - file: graph.md
            - file: standards.md
          - caption: Getting Started
            chapters:
        EOF

        for file in notebooks/L0_*.ipynb; do
          echo "    - file: $file" >> _toc.yml
        done

        echo "  - caption: Basic Functionalities" >> _toc.yml
        echo "    chapters:" >> _toc.yml
        for file in notebooks/L1_*.ipynb; do
          echo "    - file: $file" >> _toc.yml
        done

        echo "  - caption: Advanced Querying using SPARQL" >> _toc.yml
        echo "    chapters:" >> _toc.yml
        for file in notebooks/L2_*.ipynb; do
          echo "    - file: $file" >> _toc.yml
        done

        echo "  - caption: Editing LiPD files" >> _toc.yml
        echo "    chapters:" >> _toc.yml
        for file in notebooks/L3_*.ipynb; do
          echo "    - file: $file" >> _toc.yml
        done

    - name: Commit and push changes
      run: |
        git add _toc.yml
        git commit -m "Sync notebooks and update _toc.yml" || echo "No changes to commit"
        git push origin jupyterbook
